[tool.poetry]
name = "quantum_ai"
version = "0.1.0"
description = "Quantum-enhanced AI system integrating quantum computing with machine learning"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^1.26.0"  # Pin to numpy 1.x
pennylane = "^0.34.0"
torch = "^2.1.0"
fastapi = "^0.109.0"
uvicorn = "^0.27.0"
qiskit = "^0.44.0"
transformers = "^4.34.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
black = "^23.3.0"
isort = "^5.12.0"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
profile = "black"
multi_line_output = 3
