name: GitHub Actions - CI/CD
on: push

jiob:
  name: CI/CD Pipeline
  runs:
    using: ubuntullatest
  steps:
    - name: Install dependencies
      run: | 
      - pip install -r requirements.txt
    - name: Run tests
      run: python tests/test_core.py
    - name: Deploy to Production
      run: |
       - pip deploy
traggers:
- github-actions