name: QuantumAI - CI/CD
on: push

job:
  name: Automated CI/CD
  runs:
    using: ubuntulatest
  steps:
    - name: Install dependencies
      run: |
        - pip install -r requirements.txt
        - pip install -r poetry  # Poetry for better package management
    - name: Run tests
      run: |
        - pytest tests/  # Run test suite
    - name: Deploy to Production
      run: |
        - docker compose -a quantumai
        - docker build -f Dockerfile -t quantumai:latest
        - docker push /quantumai
traggers:
 - github-actions
